name: algolia Sync

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的整点执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install  

      - name: Run script
        run: node scripts.js
