name: algolia Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # 每小时的整点执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: ls
        run: ls

      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
      - name: Run script
        env:
          PSQLURL: ${{ secrets.PSQLURL}},
          ALGOLIAAPPID: ${{ secrets.ALGOLIAAPPID }},
          ALGOLIAAPIKEY: ${{ secrets.ALGOLIAAPIKEY }},
          ALGOLIAINDEXNAME: ${{ secrets.ALGOLIAINDEXNAME }}

        run: node script.js
